theme: jekyll-theme-leap-day
collections:
  creepjack_44:
    youtube_url: https://youtu.be/a1C7nq1c4Lg
    output: true
  creepjack_70:
    youtube_url: https://youtu.be/ZciOaa8atm0
    output: true
